//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgorithmConfigObservation) DeepCopyInto(out *AlgorithmConfigObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgorithmConfigObservation.
func (in *AlgorithmConfigObservation) DeepCopy() *AlgorithmConfigObservation {
	if in == nil {
		return nil
	}
	out := new(AlgorithmConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgorithmConfigParameters) DeepCopyInto(out *AlgorithmConfigParameters) {
	*out = *in
	if in.BruteForceConfig != nil {
		in, out := &in.BruteForceConfig, &out.BruteForceConfig
		*out = make([]BruteForceConfigParameters, len(*in))
		copy(*out, *in)
	}
	if in.TreeAhConfig != nil {
		in, out := &in.TreeAhConfig, &out.TreeAhConfig
		*out = make([]TreeAhConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgorithmConfigParameters.
func (in *AlgorithmConfigParameters) DeepCopy() *AlgorithmConfigParameters {
	if in == nil {
		return nil
	}
	out := new(AlgorithmConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutomaticResourcesObservation) DeepCopyInto(out *AutomaticResourcesObservation) {
	*out = *in
	if in.MaxReplicaCount != nil {
		in, out := &in.MaxReplicaCount, &out.MaxReplicaCount
		*out = new(float64)
		**out = **in
	}
	if in.MinReplicaCount != nil {
		in, out := &in.MinReplicaCount, &out.MinReplicaCount
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutomaticResourcesObservation.
func (in *AutomaticResourcesObservation) DeepCopy() *AutomaticResourcesObservation {
	if in == nil {
		return nil
	}
	out := new(AutomaticResourcesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutomaticResourcesParameters) DeepCopyInto(out *AutomaticResourcesParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutomaticResourcesParameters.
func (in *AutomaticResourcesParameters) DeepCopy() *AutomaticResourcesParameters {
	if in == nil {
		return nil
	}
	out := new(AutomaticResourcesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingMetricSpecsObservation) DeepCopyInto(out *AutoscalingMetricSpecsObservation) {
	*out = *in
	if in.MetricName != nil {
		in, out := &in.MetricName, &out.MetricName
		*out = new(string)
		**out = **in
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingMetricSpecsObservation.
func (in *AutoscalingMetricSpecsObservation) DeepCopy() *AutoscalingMetricSpecsObservation {
	if in == nil {
		return nil
	}
	out := new(AutoscalingMetricSpecsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingMetricSpecsParameters) DeepCopyInto(out *AutoscalingMetricSpecsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingMetricSpecsParameters.
func (in *AutoscalingMetricSpecsParameters) DeepCopy() *AutoscalingMetricSpecsParameters {
	if in == nil {
		return nil
	}
	out := new(AutoscalingMetricSpecsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BruteForceConfigObservation) DeepCopyInto(out *BruteForceConfigObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BruteForceConfigObservation.
func (in *BruteForceConfigObservation) DeepCopy() *BruteForceConfigObservation {
	if in == nil {
		return nil
	}
	out := new(BruteForceConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BruteForceConfigParameters) DeepCopyInto(out *BruteForceConfigParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BruteForceConfigParameters.
func (in *BruteForceConfigParameters) DeepCopy() *BruteForceConfigParameters {
	if in == nil {
		return nil
	}
	out := new(BruteForceConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CategoricalThresholdConfigObservation) DeepCopyInto(out *CategoricalThresholdConfigObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CategoricalThresholdConfigObservation.
func (in *CategoricalThresholdConfigObservation) DeepCopy() *CategoricalThresholdConfigObservation {
	if in == nil {
		return nil
	}
	out := new(CategoricalThresholdConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CategoricalThresholdConfigParameters) DeepCopyInto(out *CategoricalThresholdConfigParameters) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CategoricalThresholdConfigParameters.
func (in *CategoricalThresholdConfigParameters) DeepCopy() *CategoricalThresholdConfigParameters {
	if in == nil {
		return nil
	}
	out := new(CategoricalThresholdConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigObservation) DeepCopyInto(out *ConfigObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigObservation.
func (in *ConfigObservation) DeepCopy() *ConfigObservation {
	if in == nil {
		return nil
	}
	out := new(ConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigParameters) DeepCopyInto(out *ConfigParameters) {
	*out = *in
	if in.AlgorithmConfig != nil {
		in, out := &in.AlgorithmConfig, &out.AlgorithmConfig
		*out = make([]AlgorithmConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ApproximateNeighborsCount != nil {
		in, out := &in.ApproximateNeighborsCount, &out.ApproximateNeighborsCount
		*out = new(float64)
		**out = **in
	}
	if in.Dimensions != nil {
		in, out := &in.Dimensions, &out.Dimensions
		*out = new(float64)
		**out = **in
	}
	if in.DistanceMeasureType != nil {
		in, out := &in.DistanceMeasureType, &out.DistanceMeasureType
		*out = new(string)
		**out = **in
	}
	if in.FeatureNormType != nil {
		in, out := &in.FeatureNormType, &out.FeatureNormType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigParameters.
func (in *ConfigParameters) DeepCopy() *ConfigParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dataset) DeepCopyInto(out *Dataset) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dataset.
func (in *Dataset) DeepCopy() *Dataset {
	if in == nil {
		return nil
	}
	out := new(Dataset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dataset) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasetList) DeepCopyInto(out *DatasetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Dataset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasetList.
func (in *DatasetList) DeepCopy() *DatasetList {
	if in == nil {
		return nil
	}
	out := new(DatasetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatasetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasetObservation) DeepCopyInto(out *DatasetObservation) {
	*out = *in
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.UpdateTime != nil {
		in, out := &in.UpdateTime, &out.UpdateTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasetObservation.
func (in *DatasetObservation) DeepCopy() *DatasetObservation {
	if in == nil {
		return nil
	}
	out := new(DatasetObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasetParameters) DeepCopyInto(out *DatasetParameters) {
	*out = *in
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EncryptionSpec != nil {
		in, out := &in.EncryptionSpec, &out.EncryptionSpec
		*out = make([]EncryptionSpecParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.MetadataSchemaURI != nil {
		in, out := &in.MetadataSchemaURI, &out.MetadataSchemaURI
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasetParameters.
func (in *DatasetParameters) DeepCopy() *DatasetParameters {
	if in == nil {
		return nil
	}
	out := new(DatasetParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasetSpec) DeepCopyInto(out *DatasetSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasetSpec.
func (in *DatasetSpec) DeepCopy() *DatasetSpec {
	if in == nil {
		return nil
	}
	out := new(DatasetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasetStatus) DeepCopyInto(out *DatasetStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasetStatus.
func (in *DatasetStatus) DeepCopy() *DatasetStatus {
	if in == nil {
		return nil
	}
	out := new(DatasetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DedicatedResourcesObservation) DeepCopyInto(out *DedicatedResourcesObservation) {
	*out = *in
	if in.AutoscalingMetricSpecs != nil {
		in, out := &in.AutoscalingMetricSpecs, &out.AutoscalingMetricSpecs
		*out = make([]AutoscalingMetricSpecsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MachineSpec != nil {
		in, out := &in.MachineSpec, &out.MachineSpec
		*out = make([]MachineSpecObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MaxReplicaCount != nil {
		in, out := &in.MaxReplicaCount, &out.MaxReplicaCount
		*out = new(float64)
		**out = **in
	}
	if in.MinReplicaCount != nil {
		in, out := &in.MinReplicaCount, &out.MinReplicaCount
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DedicatedResourcesObservation.
func (in *DedicatedResourcesObservation) DeepCopy() *DedicatedResourcesObservation {
	if in == nil {
		return nil
	}
	out := new(DedicatedResourcesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DedicatedResourcesParameters) DeepCopyInto(out *DedicatedResourcesParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DedicatedResourcesParameters.
func (in *DedicatedResourcesParameters) DeepCopy() *DedicatedResourcesParameters {
	if in == nil {
		return nil
	}
	out := new(DedicatedResourcesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployedIndexesObservation) DeepCopyInto(out *DeployedIndexesObservation) {
	*out = *in
	if in.DeployedIndexID != nil {
		in, out := &in.DeployedIndexID, &out.DeployedIndexID
		*out = new(string)
		**out = **in
	}
	if in.IndexEndpoint != nil {
		in, out := &in.IndexEndpoint, &out.IndexEndpoint
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployedIndexesObservation.
func (in *DeployedIndexesObservation) DeepCopy() *DeployedIndexesObservation {
	if in == nil {
		return nil
	}
	out := new(DeployedIndexesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployedIndexesParameters) DeepCopyInto(out *DeployedIndexesParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployedIndexesParameters.
func (in *DeployedIndexesParameters) DeepCopy() *DeployedIndexesParameters {
	if in == nil {
		return nil
	}
	out := new(DeployedIndexesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployedModelsObservation) DeepCopyInto(out *DeployedModelsObservation) {
	*out = *in
	if in.AutomaticResources != nil {
		in, out := &in.AutomaticResources, &out.AutomaticResources
		*out = make([]AutomaticResourcesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.DedicatedResources != nil {
		in, out := &in.DedicatedResources, &out.DedicatedResources
		*out = make([]DedicatedResourcesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EnableAccessLogging != nil {
		in, out := &in.EnableAccessLogging, &out.EnableAccessLogging
		*out = new(bool)
		**out = **in
	}
	if in.EnableContainerLogging != nil {
		in, out := &in.EnableContainerLogging, &out.EnableContainerLogging
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(string)
		**out = **in
	}
	if in.ModelVersionID != nil {
		in, out := &in.ModelVersionID, &out.ModelVersionID
		*out = new(string)
		**out = **in
	}
	if in.PrivateEndpoints != nil {
		in, out := &in.PrivateEndpoints, &out.PrivateEndpoints
		*out = make([]PrivateEndpointsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(string)
		**out = **in
	}
	if in.SharedResources != nil {
		in, out := &in.SharedResources, &out.SharedResources
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployedModelsObservation.
func (in *DeployedModelsObservation) DeepCopy() *DeployedModelsObservation {
	if in == nil {
		return nil
	}
	out := new(DeployedModelsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployedModelsParameters) DeepCopyInto(out *DeployedModelsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployedModelsParameters.
func (in *DeployedModelsParameters) DeepCopy() *DeployedModelsParameters {
	if in == nil {
		return nil
	}
	out := new(DeployedModelsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionSpecObservation) DeepCopyInto(out *EncryptionSpecObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionSpecObservation.
func (in *EncryptionSpecObservation) DeepCopy() *EncryptionSpecObservation {
	if in == nil {
		return nil
	}
	out := new(EncryptionSpecObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionSpecParameters) DeepCopyInto(out *EncryptionSpecParameters) {
	*out = *in
	if in.KMSKeyName != nil {
		in, out := &in.KMSKeyName, &out.KMSKeyName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionSpecParameters.
func (in *EncryptionSpecParameters) DeepCopy() *EncryptionSpecParameters {
	if in == nil {
		return nil
	}
	out := new(EncryptionSpecParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Endpoint) DeepCopyInto(out *Endpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Endpoint.
func (in *Endpoint) DeepCopy() *Endpoint {
	if in == nil {
		return nil
	}
	out := new(Endpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Endpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointEncryptionSpecObservation) DeepCopyInto(out *EndpointEncryptionSpecObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointEncryptionSpecObservation.
func (in *EndpointEncryptionSpecObservation) DeepCopy() *EndpointEncryptionSpecObservation {
	if in == nil {
		return nil
	}
	out := new(EndpointEncryptionSpecObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointEncryptionSpecParameters) DeepCopyInto(out *EndpointEncryptionSpecParameters) {
	*out = *in
	if in.KMSKeyName != nil {
		in, out := &in.KMSKeyName, &out.KMSKeyName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointEncryptionSpecParameters.
func (in *EndpointEncryptionSpecParameters) DeepCopy() *EndpointEncryptionSpecParameters {
	if in == nil {
		return nil
	}
	out := new(EndpointEncryptionSpecParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointList) DeepCopyInto(out *EndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Endpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointList.
func (in *EndpointList) DeepCopy() *EndpointList {
	if in == nil {
		return nil
	}
	out := new(EndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointObservation) DeepCopyInto(out *EndpointObservation) {
	*out = *in
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.DeployedModels != nil {
		in, out := &in.DeployedModels, &out.DeployedModels
		*out = make([]DeployedModelsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Etag != nil {
		in, out := &in.Etag, &out.Etag
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ModelDeploymentMonitoringJob != nil {
		in, out := &in.ModelDeploymentMonitoringJob, &out.ModelDeploymentMonitoringJob
		*out = new(string)
		**out = **in
	}
	if in.UpdateTime != nil {
		in, out := &in.UpdateTime, &out.UpdateTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointObservation.
func (in *EndpointObservation) DeepCopy() *EndpointObservation {
	if in == nil {
		return nil
	}
	out := new(EndpointObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointParameters) DeepCopyInto(out *EndpointParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EncryptionSpec != nil {
		in, out := &in.EncryptionSpec, &out.EncryptionSpec
		*out = make([]EndpointEncryptionSpecParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointParameters.
func (in *EndpointParameters) DeepCopy() *EndpointParameters {
	if in == nil {
		return nil
	}
	out := new(EndpointParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointSpec) DeepCopyInto(out *EndpointSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointSpec.
func (in *EndpointSpec) DeepCopy() *EndpointSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointStatus) DeepCopyInto(out *EndpointStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointStatus.
func (in *EndpointStatus) DeepCopy() *EndpointStatus {
	if in == nil {
		return nil
	}
	out := new(EndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Featurestore) DeepCopyInto(out *Featurestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Featurestore.
func (in *Featurestore) DeepCopy() *Featurestore {
	if in == nil {
		return nil
	}
	out := new(Featurestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Featurestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturestoreEncryptionSpecObservation) DeepCopyInto(out *FeaturestoreEncryptionSpecObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturestoreEncryptionSpecObservation.
func (in *FeaturestoreEncryptionSpecObservation) DeepCopy() *FeaturestoreEncryptionSpecObservation {
	if in == nil {
		return nil
	}
	out := new(FeaturestoreEncryptionSpecObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturestoreEncryptionSpecParameters) DeepCopyInto(out *FeaturestoreEncryptionSpecParameters) {
	*out = *in
	if in.KMSKeyName != nil {
		in, out := &in.KMSKeyName, &out.KMSKeyName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturestoreEncryptionSpecParameters.
func (in *FeaturestoreEncryptionSpecParameters) DeepCopy() *FeaturestoreEncryptionSpecParameters {
	if in == nil {
		return nil
	}
	out := new(FeaturestoreEncryptionSpecParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturestoreEntitytype) DeepCopyInto(out *FeaturestoreEntitytype) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturestoreEntitytype.
func (in *FeaturestoreEntitytype) DeepCopy() *FeaturestoreEntitytype {
	if in == nil {
		return nil
	}
	out := new(FeaturestoreEntitytype)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FeaturestoreEntitytype) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturestoreEntitytypeFeature) DeepCopyInto(out *FeaturestoreEntitytypeFeature) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturestoreEntitytypeFeature.
func (in *FeaturestoreEntitytypeFeature) DeepCopy() *FeaturestoreEntitytypeFeature {
	if in == nil {
		return nil
	}
	out := new(FeaturestoreEntitytypeFeature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FeaturestoreEntitytypeFeature) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturestoreEntitytypeFeatureList) DeepCopyInto(out *FeaturestoreEntitytypeFeatureList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FeaturestoreEntitytypeFeature, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturestoreEntitytypeFeatureList.
func (in *FeaturestoreEntitytypeFeatureList) DeepCopy() *FeaturestoreEntitytypeFeatureList {
	if in == nil {
		return nil
	}
	out := new(FeaturestoreEntitytypeFeatureList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FeaturestoreEntitytypeFeatureList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturestoreEntitytypeFeatureObservation) DeepCopyInto(out *FeaturestoreEntitytypeFeatureObservation) {
	*out = *in
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.Etag != nil {
		in, out := &in.Etag, &out.Etag
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.UpdateTime != nil {
		in, out := &in.UpdateTime, &out.UpdateTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturestoreEntitytypeFeatureObservation.
func (in *FeaturestoreEntitytypeFeatureObservation) DeepCopy() *FeaturestoreEntitytypeFeatureObservation {
	if in == nil {
		return nil
	}
	out := new(FeaturestoreEntitytypeFeatureObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturestoreEntitytypeFeatureParameters) DeepCopyInto(out *FeaturestoreEntitytypeFeatureParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Entitytype != nil {
		in, out := &in.Entitytype, &out.Entitytype
		*out = new(string)
		**out = **in
	}
	if in.EntitytypeRef != nil {
		in, out := &in.EntitytypeRef, &out.EntitytypeRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.EntitytypeSelector != nil {
		in, out := &in.EntitytypeSelector, &out.EntitytypeSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ValueType != nil {
		in, out := &in.ValueType, &out.ValueType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturestoreEntitytypeFeatureParameters.
func (in *FeaturestoreEntitytypeFeatureParameters) DeepCopy() *FeaturestoreEntitytypeFeatureParameters {
	if in == nil {
		return nil
	}
	out := new(FeaturestoreEntitytypeFeatureParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturestoreEntitytypeFeatureSpec) DeepCopyInto(out *FeaturestoreEntitytypeFeatureSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturestoreEntitytypeFeatureSpec.
func (in *FeaturestoreEntitytypeFeatureSpec) DeepCopy() *FeaturestoreEntitytypeFeatureSpec {
	if in == nil {
		return nil
	}
	out := new(FeaturestoreEntitytypeFeatureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturestoreEntitytypeFeatureStatus) DeepCopyInto(out *FeaturestoreEntitytypeFeatureStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturestoreEntitytypeFeatureStatus.
func (in *FeaturestoreEntitytypeFeatureStatus) DeepCopy() *FeaturestoreEntitytypeFeatureStatus {
	if in == nil {
		return nil
	}
	out := new(FeaturestoreEntitytypeFeatureStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturestoreEntitytypeList) DeepCopyInto(out *FeaturestoreEntitytypeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FeaturestoreEntitytype, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturestoreEntitytypeList.
func (in *FeaturestoreEntitytypeList) DeepCopy() *FeaturestoreEntitytypeList {
	if in == nil {
		return nil
	}
	out := new(FeaturestoreEntitytypeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FeaturestoreEntitytypeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturestoreEntitytypeObservation) DeepCopyInto(out *FeaturestoreEntitytypeObservation) {
	*out = *in
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.Etag != nil {
		in, out := &in.Etag, &out.Etag
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.UpdateTime != nil {
		in, out := &in.UpdateTime, &out.UpdateTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturestoreEntitytypeObservation.
func (in *FeaturestoreEntitytypeObservation) DeepCopy() *FeaturestoreEntitytypeObservation {
	if in == nil {
		return nil
	}
	out := new(FeaturestoreEntitytypeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturestoreEntitytypeParameters) DeepCopyInto(out *FeaturestoreEntitytypeParameters) {
	*out = *in
	if in.Featurestore != nil {
		in, out := &in.Featurestore, &out.Featurestore
		*out = new(string)
		**out = **in
	}
	if in.FeaturestoreRef != nil {
		in, out := &in.FeaturestoreRef, &out.FeaturestoreRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.FeaturestoreSelector != nil {
		in, out := &in.FeaturestoreSelector, &out.FeaturestoreSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.MonitoringConfig != nil {
		in, out := &in.MonitoringConfig, &out.MonitoringConfig
		*out = make([]MonitoringConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturestoreEntitytypeParameters.
func (in *FeaturestoreEntitytypeParameters) DeepCopy() *FeaturestoreEntitytypeParameters {
	if in == nil {
		return nil
	}
	out := new(FeaturestoreEntitytypeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturestoreEntitytypeSpec) DeepCopyInto(out *FeaturestoreEntitytypeSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturestoreEntitytypeSpec.
func (in *FeaturestoreEntitytypeSpec) DeepCopy() *FeaturestoreEntitytypeSpec {
	if in == nil {
		return nil
	}
	out := new(FeaturestoreEntitytypeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturestoreEntitytypeStatus) DeepCopyInto(out *FeaturestoreEntitytypeStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturestoreEntitytypeStatus.
func (in *FeaturestoreEntitytypeStatus) DeepCopy() *FeaturestoreEntitytypeStatus {
	if in == nil {
		return nil
	}
	out := new(FeaturestoreEntitytypeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturestoreList) DeepCopyInto(out *FeaturestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Featurestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturestoreList.
func (in *FeaturestoreList) DeepCopy() *FeaturestoreList {
	if in == nil {
		return nil
	}
	out := new(FeaturestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FeaturestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturestoreObservation) DeepCopyInto(out *FeaturestoreObservation) {
	*out = *in
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.Etag != nil {
		in, out := &in.Etag, &out.Etag
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.UpdateTime != nil {
		in, out := &in.UpdateTime, &out.UpdateTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturestoreObservation.
func (in *FeaturestoreObservation) DeepCopy() *FeaturestoreObservation {
	if in == nil {
		return nil
	}
	out := new(FeaturestoreObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturestoreParameters) DeepCopyInto(out *FeaturestoreParameters) {
	*out = *in
	if in.EncryptionSpec != nil {
		in, out := &in.EncryptionSpec, &out.EncryptionSpec
		*out = make([]FeaturestoreEncryptionSpecParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ForceDestroy != nil {
		in, out := &in.ForceDestroy, &out.ForceDestroy
		*out = new(bool)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OnlineServingConfig != nil {
		in, out := &in.OnlineServingConfig, &out.OnlineServingConfig
		*out = make([]OnlineServingConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturestoreParameters.
func (in *FeaturestoreParameters) DeepCopy() *FeaturestoreParameters {
	if in == nil {
		return nil
	}
	out := new(FeaturestoreParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturestoreSpec) DeepCopyInto(out *FeaturestoreSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturestoreSpec.
func (in *FeaturestoreSpec) DeepCopy() *FeaturestoreSpec {
	if in == nil {
		return nil
	}
	out := new(FeaturestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturestoreStatus) DeepCopyInto(out *FeaturestoreStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturestoreStatus.
func (in *FeaturestoreStatus) DeepCopy() *FeaturestoreStatus {
	if in == nil {
		return nil
	}
	out := new(FeaturestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportFeaturesAnalysisObservation) DeepCopyInto(out *ImportFeaturesAnalysisObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportFeaturesAnalysisObservation.
func (in *ImportFeaturesAnalysisObservation) DeepCopy() *ImportFeaturesAnalysisObservation {
	if in == nil {
		return nil
	}
	out := new(ImportFeaturesAnalysisObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportFeaturesAnalysisParameters) DeepCopyInto(out *ImportFeaturesAnalysisParameters) {
	*out = *in
	if in.AnomalyDetectionBaseline != nil {
		in, out := &in.AnomalyDetectionBaseline, &out.AnomalyDetectionBaseline
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportFeaturesAnalysisParameters.
func (in *ImportFeaturesAnalysisParameters) DeepCopy() *ImportFeaturesAnalysisParameters {
	if in == nil {
		return nil
	}
	out := new(ImportFeaturesAnalysisParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Index) DeepCopyInto(out *Index) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Index.
func (in *Index) DeepCopy() *Index {
	if in == nil {
		return nil
	}
	out := new(Index)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Index) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexList) DeepCopyInto(out *IndexList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Index, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexList.
func (in *IndexList) DeepCopy() *IndexList {
	if in == nil {
		return nil
	}
	out := new(IndexList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IndexList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexObservation) DeepCopyInto(out *IndexObservation) {
	*out = *in
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.DeployedIndexes != nil {
		in, out := &in.DeployedIndexes, &out.DeployedIndexes
		*out = make([]DeployedIndexesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Etag != nil {
		in, out := &in.Etag, &out.Etag
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IndexStats != nil {
		in, out := &in.IndexStats, &out.IndexStats
		*out = make([]IndexStatsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MetadataSchemaURI != nil {
		in, out := &in.MetadataSchemaURI, &out.MetadataSchemaURI
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.UpdateTime != nil {
		in, out := &in.UpdateTime, &out.UpdateTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexObservation.
func (in *IndexObservation) DeepCopy() *IndexObservation {
	if in == nil {
		return nil
	}
	out := new(IndexObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexParameters) DeepCopyInto(out *IndexParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.IndexUpdateMethod != nil {
		in, out := &in.IndexUpdateMethod, &out.IndexUpdateMethod
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make([]MetadataParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexParameters.
func (in *IndexParameters) DeepCopy() *IndexParameters {
	if in == nil {
		return nil
	}
	out := new(IndexParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexSpec) DeepCopyInto(out *IndexSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexSpec.
func (in *IndexSpec) DeepCopy() *IndexSpec {
	if in == nil {
		return nil
	}
	out := new(IndexSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexStatsObservation) DeepCopyInto(out *IndexStatsObservation) {
	*out = *in
	if in.ShardsCount != nil {
		in, out := &in.ShardsCount, &out.ShardsCount
		*out = new(float64)
		**out = **in
	}
	if in.VectorsCount != nil {
		in, out := &in.VectorsCount, &out.VectorsCount
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexStatsObservation.
func (in *IndexStatsObservation) DeepCopy() *IndexStatsObservation {
	if in == nil {
		return nil
	}
	out := new(IndexStatsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexStatsParameters) DeepCopyInto(out *IndexStatsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexStatsParameters.
func (in *IndexStatsParameters) DeepCopy() *IndexStatsParameters {
	if in == nil {
		return nil
	}
	out := new(IndexStatsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexStatus) DeepCopyInto(out *IndexStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexStatus.
func (in *IndexStatus) DeepCopy() *IndexStatus {
	if in == nil {
		return nil
	}
	out := new(IndexStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineSpecObservation) DeepCopyInto(out *MachineSpecObservation) {
	*out = *in
	if in.AcceleratorCount != nil {
		in, out := &in.AcceleratorCount, &out.AcceleratorCount
		*out = new(float64)
		**out = **in
	}
	if in.AcceleratorType != nil {
		in, out := &in.AcceleratorType, &out.AcceleratorType
		*out = new(string)
		**out = **in
	}
	if in.MachineType != nil {
		in, out := &in.MachineType, &out.MachineType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineSpecObservation.
func (in *MachineSpecObservation) DeepCopy() *MachineSpecObservation {
	if in == nil {
		return nil
	}
	out := new(MachineSpecObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineSpecParameters) DeepCopyInto(out *MachineSpecParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineSpecParameters.
func (in *MachineSpecParameters) DeepCopy() *MachineSpecParameters {
	if in == nil {
		return nil
	}
	out := new(MachineSpecParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataObservation) DeepCopyInto(out *MetadataObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataObservation.
func (in *MetadataObservation) DeepCopy() *MetadataObservation {
	if in == nil {
		return nil
	}
	out := new(MetadataObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataParameters) DeepCopyInto(out *MetadataParameters) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]ConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ContentsDeltaURI != nil {
		in, out := &in.ContentsDeltaURI, &out.ContentsDeltaURI
		*out = new(string)
		**out = **in
	}
	if in.IsCompleteOverwrite != nil {
		in, out := &in.IsCompleteOverwrite, &out.IsCompleteOverwrite
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataParameters.
func (in *MetadataParameters) DeepCopy() *MetadataParameters {
	if in == nil {
		return nil
	}
	out := new(MetadataParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringConfigObservation) DeepCopyInto(out *MonitoringConfigObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringConfigObservation.
func (in *MonitoringConfigObservation) DeepCopy() *MonitoringConfigObservation {
	if in == nil {
		return nil
	}
	out := new(MonitoringConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringConfigParameters) DeepCopyInto(out *MonitoringConfigParameters) {
	*out = *in
	if in.CategoricalThresholdConfig != nil {
		in, out := &in.CategoricalThresholdConfig, &out.CategoricalThresholdConfig
		*out = make([]CategoricalThresholdConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ImportFeaturesAnalysis != nil {
		in, out := &in.ImportFeaturesAnalysis, &out.ImportFeaturesAnalysis
		*out = make([]ImportFeaturesAnalysisParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NumericalThresholdConfig != nil {
		in, out := &in.NumericalThresholdConfig, &out.NumericalThresholdConfig
		*out = make([]NumericalThresholdConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SnapshotAnalysis != nil {
		in, out := &in.SnapshotAnalysis, &out.SnapshotAnalysis
		*out = make([]SnapshotAnalysisParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringConfigParameters.
func (in *MonitoringConfigParameters) DeepCopy() *MonitoringConfigParameters {
	if in == nil {
		return nil
	}
	out := new(MonitoringConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NumericalThresholdConfigObservation) DeepCopyInto(out *NumericalThresholdConfigObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NumericalThresholdConfigObservation.
func (in *NumericalThresholdConfigObservation) DeepCopy() *NumericalThresholdConfigObservation {
	if in == nil {
		return nil
	}
	out := new(NumericalThresholdConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NumericalThresholdConfigParameters) DeepCopyInto(out *NumericalThresholdConfigParameters) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NumericalThresholdConfigParameters.
func (in *NumericalThresholdConfigParameters) DeepCopy() *NumericalThresholdConfigParameters {
	if in == nil {
		return nil
	}
	out := new(NumericalThresholdConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnlineServingConfigObservation) DeepCopyInto(out *OnlineServingConfigObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnlineServingConfigObservation.
func (in *OnlineServingConfigObservation) DeepCopy() *OnlineServingConfigObservation {
	if in == nil {
		return nil
	}
	out := new(OnlineServingConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnlineServingConfigParameters) DeepCopyInto(out *OnlineServingConfigParameters) {
	*out = *in
	if in.FixedNodeCount != nil {
		in, out := &in.FixedNodeCount, &out.FixedNodeCount
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnlineServingConfigParameters.
func (in *OnlineServingConfigParameters) DeepCopy() *OnlineServingConfigParameters {
	if in == nil {
		return nil
	}
	out := new(OnlineServingConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointsObservation) DeepCopyInto(out *PrivateEndpointsObservation) {
	*out = *in
	if in.ExplainHTTPURI != nil {
		in, out := &in.ExplainHTTPURI, &out.ExplainHTTPURI
		*out = new(string)
		**out = **in
	}
	if in.HealthHTTPURI != nil {
		in, out := &in.HealthHTTPURI, &out.HealthHTTPURI
		*out = new(string)
		**out = **in
	}
	if in.PredictHTTPURI != nil {
		in, out := &in.PredictHTTPURI, &out.PredictHTTPURI
		*out = new(string)
		**out = **in
	}
	if in.ServiceAttachment != nil {
		in, out := &in.ServiceAttachment, &out.ServiceAttachment
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointsObservation.
func (in *PrivateEndpointsObservation) DeepCopy() *PrivateEndpointsObservation {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointsParameters) DeepCopyInto(out *PrivateEndpointsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointsParameters.
func (in *PrivateEndpointsParameters) DeepCopy() *PrivateEndpointsParameters {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotAnalysisObservation) DeepCopyInto(out *SnapshotAnalysisObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotAnalysisObservation.
func (in *SnapshotAnalysisObservation) DeepCopy() *SnapshotAnalysisObservation {
	if in == nil {
		return nil
	}
	out := new(SnapshotAnalysisObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotAnalysisParameters) DeepCopyInto(out *SnapshotAnalysisParameters) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.MonitoringIntervalDays != nil {
		in, out := &in.MonitoringIntervalDays, &out.MonitoringIntervalDays
		*out = new(float64)
		**out = **in
	}
	if in.StalenessDays != nil {
		in, out := &in.StalenessDays, &out.StalenessDays
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotAnalysisParameters.
func (in *SnapshotAnalysisParameters) DeepCopy() *SnapshotAnalysisParameters {
	if in == nil {
		return nil
	}
	out := new(SnapshotAnalysisParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tensorboard) DeepCopyInto(out *Tensorboard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tensorboard.
func (in *Tensorboard) DeepCopy() *Tensorboard {
	if in == nil {
		return nil
	}
	out := new(Tensorboard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tensorboard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TensorboardEncryptionSpecObservation) DeepCopyInto(out *TensorboardEncryptionSpecObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TensorboardEncryptionSpecObservation.
func (in *TensorboardEncryptionSpecObservation) DeepCopy() *TensorboardEncryptionSpecObservation {
	if in == nil {
		return nil
	}
	out := new(TensorboardEncryptionSpecObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TensorboardEncryptionSpecParameters) DeepCopyInto(out *TensorboardEncryptionSpecParameters) {
	*out = *in
	if in.KMSKeyName != nil {
		in, out := &in.KMSKeyName, &out.KMSKeyName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TensorboardEncryptionSpecParameters.
func (in *TensorboardEncryptionSpecParameters) DeepCopy() *TensorboardEncryptionSpecParameters {
	if in == nil {
		return nil
	}
	out := new(TensorboardEncryptionSpecParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TensorboardList) DeepCopyInto(out *TensorboardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tensorboard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TensorboardList.
func (in *TensorboardList) DeepCopy() *TensorboardList {
	if in == nil {
		return nil
	}
	out := new(TensorboardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TensorboardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TensorboardObservation) DeepCopyInto(out *TensorboardObservation) {
	*out = *in
	if in.BlobStoragePathPrefix != nil {
		in, out := &in.BlobStoragePathPrefix, &out.BlobStoragePathPrefix
		*out = new(string)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RunCount != nil {
		in, out := &in.RunCount, &out.RunCount
		*out = new(string)
		**out = **in
	}
	if in.UpdateTime != nil {
		in, out := &in.UpdateTime, &out.UpdateTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TensorboardObservation.
func (in *TensorboardObservation) DeepCopy() *TensorboardObservation {
	if in == nil {
		return nil
	}
	out := new(TensorboardObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TensorboardParameters) DeepCopyInto(out *TensorboardParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EncryptionSpec != nil {
		in, out := &in.EncryptionSpec, &out.EncryptionSpec
		*out = make([]TensorboardEncryptionSpecParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TensorboardParameters.
func (in *TensorboardParameters) DeepCopy() *TensorboardParameters {
	if in == nil {
		return nil
	}
	out := new(TensorboardParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TensorboardSpec) DeepCopyInto(out *TensorboardSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TensorboardSpec.
func (in *TensorboardSpec) DeepCopy() *TensorboardSpec {
	if in == nil {
		return nil
	}
	out := new(TensorboardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TensorboardStatus) DeepCopyInto(out *TensorboardStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TensorboardStatus.
func (in *TensorboardStatus) DeepCopy() *TensorboardStatus {
	if in == nil {
		return nil
	}
	out := new(TensorboardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TreeAhConfigObservation) DeepCopyInto(out *TreeAhConfigObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TreeAhConfigObservation.
func (in *TreeAhConfigObservation) DeepCopy() *TreeAhConfigObservation {
	if in == nil {
		return nil
	}
	out := new(TreeAhConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TreeAhConfigParameters) DeepCopyInto(out *TreeAhConfigParameters) {
	*out = *in
	if in.LeafNodeEmbeddingCount != nil {
		in, out := &in.LeafNodeEmbeddingCount, &out.LeafNodeEmbeddingCount
		*out = new(float64)
		**out = **in
	}
	if in.LeafNodesToSearchPercent != nil {
		in, out := &in.LeafNodesToSearchPercent, &out.LeafNodesToSearchPercent
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TreeAhConfigParameters.
func (in *TreeAhConfigParameters) DeepCopy() *TreeAhConfigParameters {
	if in == nil {
		return nil
	}
	out := new(TreeAhConfigParameters)
	in.DeepCopyInto(out)
	return out
}
